### PR TITLE
Update to work with the new Github Look

### PR DESCRIPTION
**Pull request by lukeberry99**
All credit to @fnkr
https://community.c9.io/t/cloud9-button-for-github-does-not-work-with-githubs-new-repository-look/528
https://gist.github.com/fnkr/830e2edc27af2005fb12

### CODE REVIEW

**Comment by nightwing** [comment]
Thanks!

**Comment by fnkr** [comment]
Can *someone* please upload the new version to the Chrome Webstore?

**Comment by lukeberry99** [comment]
Would if I could, paging @nightwing and @fjakobs

**Comment by nightwing** [comment]
done

**Pull request merged**
